### PR TITLE
More fixes for Result and Parser

### PR DESCRIPTION
**Pull request by novemberkilo**
For Result: I think you meant Fold instead of FlatMap for the advanced version of Map?

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
@markhibberd @novemberkilo does this just require rebasing then merging?

**Comment by markhibberd** [comment]
@tmcgilchrist Yep.

**Comment by novemberkilo** [comment]
@tmcgilchrist @markhibberd rebased on master as suggested

**Comment by tmcgilchrist** [comment]
Cheers :bee:

**Pull request merged**
